# Functions for Gene Expressions

Define a function to normalize the expression data using a method called RPKM normalization.  This allows the comparison of measurements between different samples and genes.

<div class="alert alert-block alert-info">
In this case, we want ot highlight NumPy's vectorization and broadcasting rules, which allow us to manipulate and reason about data arrays very efficiently.
</div>

In [1]:
import numpy as np

In [2]:
def rpkm(counts, lengths):
    """Calculate reads per kilobase transcript per million reads.
    
    RPKM = (10^9 * C) / (N * L)
    
    Where:
    C = Number of reads mapped to a gene
    N = Total mapped reads in the experiment
    L = Exon length in base pairs for a gene
    
    Parameters
    ----------
    counts: array, shape (N_genes, N_samples)
        RNAseq (or similar) count data where columns are individual samples and rows are genes.
    lengths: array, shape (N_genes,)
        Gene lengths in base pairs in the same order as the rows in counts.
        
    Returns
    -------
    normed: array, shape (N_genes, N_samples)
        The RPKM normalized counts matrix.
    """
    
    N = np.sum(counts, axis=0)    # sum each column to get total reads per sample
    L = lengths
    C = counts
    
    normed = 1e9 * C / (N[np.newaxis, :] * L[:, np.newaxis])
    
    return(normed)

Make gene expression a list of lists.

In [3]:
gene0 = [100, 200]
gene1 = [50, 0]
gene2 = [350, 100]
expression_data = [gene0, gene1, gene2]

In [4]:
expression_data[2][0]

350

NumPy N-Dimensional Arrays

In [5]:
array1d = np.array([1,2,3,4])
print(array1d)
print(type(array1d))
print(array1d.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [6]:
array2d = np.array(expression_data)
print(array2d)
print(array2d.shape)
print(type(array2d))

[[100 200]
 [ 50   0]
 [350 100]]
(3, 2)
<class 'numpy.ndarray'>


<div class="alert alert-block alert-success">
This demonstrates that the shape function accounts for multi-dimensional arrays whereas len does not.
</div>

In [7]:
print(array2d.ndim)

2


## Why Use ndarrays Instead of Python Lists?

In [8]:
# Create an ndarray of integers in the range
# 0 up to (but not including) 1,000,000
array = np.arange(1e6)
list_array = array.tolist()

In [9]:
%timeit -n10 y = [val*5 for val in list_array]

86.5 ms ± 5.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit -n10 x = array * 5

2.26 ms ± 889 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


<div class="alert alert-block alert-success">
Using numpy array makes the calculation 50x faster than a list comprehension on a list.
</div>

Ndarrays are more memory efficient than lists, using only the minimal memory needed for what is in the array.  You can use slices of arrays without making a copy.  If you modify this assignment it will change the original array.

In [11]:
# Create an ndarray x
x = np.array([1, 2, 3], np.int32)
print(x)

[1 2 3]


In [12]:
# Create a "slice" of x
y = x[:2]
print(y)

[1 2]


In [13]:
# Set the first element of y to be 6
y[0] = 6
print(y)

[6 2]


In [14]:
# Now the first element in x has changed to 6!
print(x)

[6 2 3]


<div class="alert alert-block alert-danger">
Notice that although we edited y, x has also changed, because y was referencing the smae data!</div>

In [15]:
# You must be careful with array references, to make a copy
y = np.copy(x[:2])

## Vectorization

Apply a calculation to each element in an array without having to use a for loop.  This will also result in more readable code.

In [16]:
x = np.array([1, 2, 3, 4])
print(x * 2)

[2 4 6 8]


In [17]:
y = np.array([0, 1, 2, 1])
print(x + y)

[1 3 5 5]


## Broadcasting

Broadcasting is a way of performing implicit operations between two arrays, allowing you to perform operations on arrays of *compatible* shapes, to create arrays bigger than either of the starting ones.

In [18]:
x = np.array([1, 2, 3, 4])
x = np.reshape(x, (len(x), 1))
print(x)

[[1]
 [2]
 [3]
 [4]]


In [19]:
x.shape

(4, 1)

In [20]:
y = np.array([0, 1, 2, 1])
y = np.reshape(y, [1, len(y)])
print(y)

[[0 1 2 1]]


In [21]:
y.shape

(1, 4)

In [22]:
outer = x * y
print(outer)

[[0 1 2 1]
 [0 2 4 2]
 [0 3 6 3]
 [0 4 8 4]]


In [23]:
print(outer.shape)

(4, 4)


## Exploring a Gene Expressions Dataset

In [24]:
import pandas as pd

In [47]:
ls ElegantSciPy/data

counts.txt.bz2  genes.csv


In [49]:
# Import TCGA malanoma data
filename = 'ElegantSciPy/data/counts.txt.bz2'
with open(filename, 'rt') as f:
    data_table = pd.read_csv(f, index_col=0)    # Parse file with pandas

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 17: invalid continuation byte

In [32]:
print(data_table.iloc[:5, :5])

       00624286-41dd-476f-a63b-d2a5f484bb45  TCGA-FS-A1Z0  TCGA-D9-A3Z1  \
A1BG                                1272.36        452.96        288.06   
A1CF                                   0.00          0.00          0.00   
A2BP1                                  0.00          0.00          0.00   
A2LD1                                164.38        552.43        201.83   
A2ML1                                 27.00          0.00          0.00   

       02c76d24-f1d2-4029-95b4-8be3bda8fdbe  TCGA-EB-A51B  
A1BG                                 400.11        420.46  
A1CF                                   1.00          0.00  
A2BP1                                  0.00          1.00  
A2LD1                                165.12         95.75  
A2ML1                                  0.00          8.00  


In [33]:
# Sample names
samples = list(data_table.columns)

In [36]:
filename = 'ElegantSciPy/data/genes.csv'
with open(filename, 'rt') as f:    # Parse file with pandas, index by GeneSymbol
    gene_info = pd.read_csv(f, index_col=0)
print(gene_info)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 76, saw 8
